Enhancement/web release
NASAWorldWind/NASAWorldWind.github.io pull request #123
Opened 2017-11-06 23:53 UTC by eirizarry

Closes #121, #122 

- Link to "GitHub releases" on Web WorldWind overview has been fixed
- Page title and panel titles under Web WW tutorials have been decoupled
     - I added in a new Param to the front matter called "header", then changed the "panel-list.html" to call the page header rather than the page title.

2017-11-07 00:25 UTC, pdavidc requested changes
Nicely done. Looks like the Java and Android list content need header values as well.

2017-11-08 20:46 UTC, eirizarry commented
I have also made notes to put configuration.js and the Simplest Example in "Tutorials".

2017-11-08 21:47 UTC, pdavidc commented
Very good first iteration for Web WorldWind's examples.

For the next iteration on examples, I have two thoughts:
• We want to capture all of the examples.
• We want to use Hugo's list-based content population, like tutorials.

2017-11-08 21:47 UTC, pdavidc approved these changes

2017-11-08 21:47 UTC, merged