Add event tracking to website
NASAWorldWind/NASAWorldWind.github.io pull request #135
Opened 2017-12-07 01:22 UTC by eirizarry

Second attempt to add event tracking to website. This has been successfully tested in dev. 

- Moved the ga event tracking code to page header of baseof.html. Keeping the ga code with the original tracking snippet still works, but google docs said it should be in a page header rather than in same file. 

- Added onclick attribute to Web links on Overview and Get Started pages. 

Still working on a solution for adding this feature to the Web Examples. Next iteration will also include this feature for the Java, Android, and Server Kit pages.

2017-12-07 02:55 UTC, pdavidc requested changes
Explicitly modifying every link to support outbound tracking is going to be difficult to maintain. Let's try doing something at the DOM level, such as these suggestions:
https://stackoverflow.com/questions/8492344/javascript-attach-an-onclick-event-to-all-links

2017-12-14 01:19 UTC, eirizarry commented
I successfully added event tracking at the DOM level, but I have run into another problem. First, this tracking is also going to include internal clicks. In the example report below, you can see that everything I click on to go to another site page is recorded. This tracking is redundant because we can already see what pages people are viewing. 

![screen shot 2017-12-13 at 4 11 23 pm](https://user-images.githubusercontent.com/23271817/33970590-b1986f4a-e028-11e7-81a7-a3b6283caa27.png)

I am wondering if there is a way to exclude the internal clicks? Something like: 

     if (domainName includes worldwind.arc.nasa.gov) { 
          exclude 'click'
     }
     else {
          function handleOutboundLinkClicks()
     }

This also does not accurately track clicking on Web examples, or Android examples and tutorials--the label is reported as (not set)--see above. Even though the pages are rendered as html, and I am using getElementsByTagName, all these instances were written as Hugo shortcodes. 

@zglueck, do you have any guidance on this?

2017-12-14 20:28 UTC, eirizarry commented
@zglueck was able to help me solve the remaining issues. Everything has been successfully tested.

2017-12-15 00:31 UTC, zglueck requested changes
I overlooked a simpler approach this afternoon. Take a look at the `event.currentTarget.href` property. It looks like it would eliminate the recursive search.

2017-12-15 22:54 UTC, pdavidc approved these changes

2017-12-15 22:55 UTC, pdavidc commented
@zglueck Have you had a chance to review the current state of this pull request?

2017-12-15 22:57 UTC, zglueck approved these changes
Looks good!

2017-12-15 23:09 UTC, merged