Add webworldwind.org overview and features content
NASAWorldWind/NASAWorldWind.github.io pull request #46
Opened 2017-07-17 03:45 UTC by zglueck

This pull request closes #28 by porting the Overview and Features content from webworldwind.org.

Most of the content is ported word for word; however, there is a special **Download** section which makes a general note of how to build the library locally as the repository is setup now in the develop branch. Additionally, I've added content which makes reference to the upcoming release and NPM inclusion.

This effort supports the #14 Port external site content epic.

2017-07-19 22:11 UTC, pdavidc requested changes
Very nice beginning for Web WorldWind. Just a few changes needed.

2017-07-19 22:11 UTC, pdavidc commented on content/web/_index.md
> +*The first release of Web WorldWind is imminent, please check back soon for updates to these instructions! The versioned release will be the first official release of Web WorldWind and will be availa
This formatting makes sense conceptually, but looked odd to me.

2017-07-19 22:11 UTC, pdavidc commented on content/web/_index.md
> +For more information about integrating Web WorldWind with your site and for how to use its many features, please see the [Developer Guide](/web/developer-guide/).
Did you mean tutorials?

2017-07-19 22:11 UTC, pdavidc commented on content/web/_index.md
> +To add Web WorldWind to your web application, build the worldwind.js and worldwind.min.js files locally and host the the library in a manner which best supports your applications requirements. To bui
Could this be expressed as a simple list? It's wordy and difficult to make out what actions are needed. The result sounds a lot more complex than it is.

2017-07-25 14:36 UTC, zglueck commented
I'm closing this pull request in favor of #49 which incorporates some site architecture changes merged in other pull requests.

2017-07-25 14:36 UTC, closed without merging