Add WWSK content section to website
NASAWorldWind/NASAWorldWind.github.io pull request #99
Opened 2017-09-19 19:24 UTC by eirizarry

This PR will add a section for the WorldWind Server Kit to our website. 

Content includes: 
- Home
- Get Started
- Features
- Examples (under construction)
- Docs

This iteration is designed to meet the requirements for presenting WWSK at EO Open Science. The "Docs" page only contains information on WWSK modules for now. There is no content on "Examples", except for a disclaimer that the page is under construction. If there is no need to add examples right now, I will remove it. I believe there is more documentation to be added; my suggestion is to merge this now and submit new documentation through a new PR.

2017-09-19 21:58 UTC, emxsys reviewed
Just a few minor edits are needed.

2017-09-19 21:58 UTC, emxsys commented on content/serverkit/_index.md
> +[GeoServer](http://geoserver.org/) for easy data distribution and implementation. It is designed with simplicity in mind.
Please strike the word 'data' in "for easy data distribution"

2017-09-19 21:58 UTC, emxsys commented on content/serverkit/docs/modules.md
> +[WorldWind GeoServer WMS Module](https://github.com/NASAWorldWind/WorldWindServerKit/tree/develop/worldwind-gs-wms)
There is an additional module to add: WorldWind GeoServer Viewer (or Explorer, TBD). It's under development in the feature/#107-worldwind_viewer branch

2017-09-19 21:58 UTC, emxsys commented on content/serverkit/features.md
> +- Visualizes all the layers/layer groups that you've defined on one terrain
Please change "layers/layer groups" to "layers and layer groups"

2017-09-19 22:02 UTC, emxsys commented
Please keep the Examples section as I think it will be applicable, for instance, how to setup a Cascaded WMS to WorldWind servers.

2017-09-20 17:11 UTC, pdavidc requested changes
This is coming along very nicely. I see a need for a few changes:

- Get Started, Features, Examples, and Docs don't have the project header, which I found disorienting.
- Get Started section titles may be better as "Build", and "Run", respectively.
- Examples section: @emxsys mentioned keeping this section in an earlier comment, but I'm out of the loop on what that looked like initially. Is there any action needed to address this section?

2017-09-20 23:11 UTC, pdavidc commented
Looks great!

2017-09-20 23:11 UTC, pdavidc approved these changes

2017-09-20 23:11 UTC, merged